### ISSUE TITLE
componentWillMount

### ISSUE THREAD

**Issue by mp1pro** [powernerd/jammming#3]
It is not best practice to store a function inside the constructor like this

```
class App extends React.Component {
  constructor(props) {
    super(props);
..........................................
    Spotify.getAccessToken();
}
}
```

The best place to put it is in componentWillMount. That will trigger the function as soon as its loaded. You can can get more information on that here;

https://reactjs.org/docs/react-component.html

**Comment by powernerd** [comment]
Thanks for the feedback. After reading this issue, and the reactjs.org docs I googled for a little more and found this: https://daveceddia.com/where-fetch-data-componentwillmount-vs-componentdidmount/

Splitting hairs here. After reading the above article, do you agree that [componentDidMount](https://reactjs.org/docs/react-component.html#componentdidmount) is the correct place to move the code to? 
Hypothetical: in the event that my Chief Marketing Officer of Jammming Inc. says we need to work on our SEO, we would probably add server side rendering. We wouldn't need to trigger the `Spotify.getAccessToken();` code more than once. 
Although,  it's coded to retrieve the value from memory if it can so it probably doesn't matter *at all anyway*.

**Comment by mp1pro** [comment]
Every use case is different. For this app, set the initial state for accessToken in constructor and use `componentWillMount` with` setState` with `Spotify.getAccessToken()` . You can also render react as a string to the DOM so that no components are triggered for SEO purposes. The article needs updating, I follow this author too, Also go through the comments of that article. 

For further help, contact a react adviser @ http://codecademy.com
